(define (aplusb a b)
  (+ a b))
(define (square a)
  (* a a))
(define (sum-of-square a b)
  (+ (* a a)
     (* b b)))
(define (sqrt-iter guess x)
  (if (good-enough? guess x)
      guess
      (sqrt-iter (improve guess x)
                 x)))
(define (improve guess x)
  (average guess (/ x guess)))
(define (average x y)
  (/ (+ x y) 2))
(define (good-enough? guess x)
  (< (/ (abs (- (square guess) x))
        x)
     0.0000001))
(define (newton x)
  (sqrt-iter 1.0 x))