(define (even a) (= (remainder a 2) 0))
(define (square a) (* a a))
(define (qsm a b)
  (cond ((= b 0) 1)
        ((even b) (square (qsm a (/ b 2))))
        (else (* a (qsm a (- b 1))))))
(define (qsmm a b m)
  (cond ((= b 0) 1)
        ((even b) (remainder (square (qsm a (/ b 2))) m))
        (else (remainder (* a (qsm a (- b 1))) m ))))